openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Arch Lab Example API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8081
    description: Example server
paths:
  /auth:
    get:
      summary: Проверка аутентификации
      responses:
        '200':
          description: User ID
          content:
            application/json:
              schema:
               type: string
        401:
          description: Not authentication
          content:
            application/json:
              schema:
                type: string
  /cart_by_owner:
    get:
      summary: Чтение информации о корзине
      parameters:
      - name: owner_id
        description: id владельца
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/cart_id'
      responses:
        '200':
          description: Найденный пользователь
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cart'
        404:
          description: Пользователь не найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /create_cart:
    post:
      summary: Создание корзины
      parameters:
      - name: owner_id
        description: id владельца
        in: query
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Идентификатор, добавленного пользователя
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    cart_id:
      description: Уникальный идентификатор корзины
      type: integer
    cart:
      type: object
      required:
        - id
        - owner_id
      properties:
        id:
          $ref: '#/components/schemas/cart_id'
        owner_id:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []