openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'cart_service API'
  description: Пример API для первого домашнего задания по курсу Архитектура программных систем
servers:
  - url: http://localhost:8081
    description: Cart_service
paths:
  /cart_by_owner:
    get:
      summary: Чтение информации о корзине
      parameters:
      - name: owner_id
        description: Чтение информации о корзине
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Найденная корзина
          content:
            application/json:
              schema:
                type: string
        404:
          description: Корзина не найдена
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /add_item:
    post:
      summary: Добавление товара в корзину
      parameters:
      - name: owner_id
        description: id владельца корзины
        in: query
        required: true
        schema:
          type: integer
      - name: item_id
        description: id товара
        in: query
        required: true
        schema:
          type: integer
      - name: amount
        description: Количество товара
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Идентификатор корзины
          content:
            application/json:
              schema:
                type: integer
        404:
          description: Ошибка добавления товара
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        500:
          description: Неожиданная ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /create_cart:
      post:
        summary: Создание корзины
        parameters:
        - name: owner_id
          description: Идентификатор владельца
          in: query
          required: true
          schema:
            type: integer
        responses:
          '200':
            description: Идентификатор, добавленной корзины
            content:
              application/json:
                schema:
                  type: integer
          404:
            description: Ошибка добавления корзины
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
          500:
            description: Неожиданная ошибка
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Error'
components:
  schemas:
    cart_id:
      description: Уникальный идентификатор корзины
      type: integer
    cart:
      type: object
      required:
        - id
        - owner_id
      properties:
        id:
          $ref: '#/components/schemas/cart_id'
        owner_id:
          type: integer
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: Сообщение о ошибке
          type: string
  securitySchemes:
      basicAuth:     
        type: http
        scheme: basic
security:
  - basicAuth: []